import { readFile } from "node:fs/promises";
import { relative } from "node:path";
import { parseTestSpec } from "../spec/parser.ts";
import { loadProjectConfig, targetConfigFor, type ProjectConfig } from "../config/project-config.ts";
import { resolveTarget } from "../targets/registry.ts";
import { resolveTestPathAbs } from "../targets/test-path.ts";
import {
  collectSupportFiles,
  loadTsconfigPaths,
  type TsconfigPaths,
} from "../targets/support-files.ts";

/**
 * The files that together make up one test case, as a drift audit sees them.
 *
 * A `deterministic` spec is two artifacts: the spec.yaml a human wrote, and the
 * code `ccqa generate` compiled from a recording. The spec describes intent in
 * prose; the generated code holds the literal selectors that actually run. They
 * drift independently, so auditing only the spec leaves the half that breaks a
 * replay unexamined.
 *
 * A `mode: live` spec has no second artifact — Claude drives it from the spec
 * every time, so the spec *is* the test.
 */
export interface SpecArtifacts {
  specYaml: string;
  /** Empty for a live spec, and for a deterministic spec that has not been generated yet. */
  generated: Array<{ path: string; content: string }>;
  /**
   * Files that belong to this test case but did not fit the byte budget. The
   * audit is told their names: a file it never saw must not read as one it
   * cleared.
   */
  unaudited: string[];
  live: boolean;
  /** Null when the spec cannot be parsed. Carried into the report so a drift row
   * reads as the test case it audited, not as its directory path. */
  title: string | null;
}

/**
 * Total generated bytes handed to the audit. Generated suites can run long, and
 * the audit's job is to check the strings they name, not to read every line —
 * but a silent cut would let it clear a file it never saw, so what is dropped
 * is always named in `unaudited`.
 */
const MAX_GENERATED_BYTES = 64 * 1024;

/**
 * What a whole sweep shares: the project's config and its import aliases.
 * Neither can change while specs are being audited, and both are read per spec
 * without this — one file read and validation each, per spec.
 */
export interface SpecArtifactsContext {
  config: ProjectConfig;
  tsconfig: TsconfigPaths | null;
}

/** Read the sweep-wide inputs once, before the first spec. */
export async function loadSpecArtifactsContext(cwd: string): Promise<SpecArtifactsContext> {
  const [config, tsconfig] = await Promise.all([loadProjectConfig(cwd), loadTsconfigPaths(cwd)]);
  return { config, tsconfig };
}

export async function collectSpecArtifacts(
  featureName: string,
  specName: string,
  specYaml: string,
  cwd: string,
  ctx: SpecArtifactsContext,
): Promise<SpecArtifacts> {
  const { live, title } = describe(specYaml);
  if (live) return { specYaml, generated: [], unaudited: [], live, title };
  const { generated, unaudited } = await readGenerated(featureName, specName, specYaml, cwd, ctx);
  return { specYaml, generated, unaudited, live, title };
}

function describe(specYaml: string): { live: boolean; title: string | null } {
  try {
    const spec = parseTestSpec(specYaml);
    return { live: spec.mode === "live", title: spec.title ?? null };
  } catch {
    // An unparsable spec is audited as-is; assuming "not live" only means the
    // generated files are looked for, which is harmless when there are none.
    return { live: false, title: null };
  }
}

/**
 * The code this spec runs: the test at the target's `testPath`, then whatever
 * it imports from inside the project. A page object names selectors too, and an
 * audit that stopped at the test file would clear strings it never read.
 */
async function readGenerated(
  featureName: string,
  specName: string,
  specYaml: string,
  cwd: string,
  ctx: SpecArtifactsContext,
): Promise<{ generated: Array<{ path: string; content: string }>; unaudited: string[] }> {
  const testAbs = testFileFor(featureName, specName, specYaml, cwd, ctx.config);
  if (testAbs === null) return { generated: [], unaudited: [] };
  const paths = [testAbs, ...(await collectSupportFiles(testAbs, cwd, { tsconfig: ctx.tsconfig }))];
  // Read together, spend the budget in order: the reads are independent, but
  // which file falls outside the budget must not depend on who finished first.
  const contents = await Promise.all(paths.map((p) => readFile(p, "utf8").catch(() => null)));

  const generated: Array<{ path: string; content: string }> = [];
  const unaudited: string[] = [];
  let used = 0;
  for (const [i, content] of contents.entries()) {
    if (content === null) continue;
    const display = relative(cwd, paths[i]!);
    if (used + content.length > MAX_GENERATED_BYTES) {
      unaudited.push(display);
      continue;
    }
    generated.push({ path: display, content });
    used += content.length;
  }
  return { generated, unaudited };
}

/**
 * Where this spec's test lives, resolved through its target. A spec that will
 * not parse, or whose target cannot be resolved, has no test path to derive —
 * the audit then reads the spec alone rather than guessing at a file.
 */
function testFileFor(
  featureName: string,
  specName: string,
  specYaml: string,
  cwd: string,
  config: ProjectConfig,
): string | null {
  try {
    const spec = parseTestSpec(specYaml);
    const target = resolveTarget(spec, config);
    const targetConfig = targetConfigFor(config, target.id);
    return resolveTestPathAbs(target, targetConfig, { featureName, specName }, cwd);
  } catch {
    return null;
  }
}
