import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { parseTestSpec } from "../spec/parser.ts";
import { getSpecDir } from "../store/index.ts";
import { GENERATED_MANIFEST_FILE, GeneratedManifestSchema } from "../targets/run-command-runner.ts";

/**
 * The files that together make up one test case, as a drift audit sees them.
 *
 * A `deterministic` spec is two artifacts: the spec.yaml a human wrote, and the
 * code `ccqa generate` compiled from a recording. The spec describes intent in
 * prose; the generated code holds the literal selectors that actually run. They
 * drift independently, so auditing only the spec leaves the half that breaks a
 * replay unexamined.
 *
 * A `mode: live` spec has no second artifact — Claude drives it from the spec
 * every time, so the spec *is* the test.
 */
export interface SpecArtifacts {
  specYaml: string;
  /** Empty for a live spec, and for a deterministic spec that has not been generated yet. */
  generated: Array<{ path: string; content: string }>;
  live: boolean;
}

/**
 * Total generated bytes handed to the audit. Generated suites can run long, and
 * the audit's job is to check the strings they name, not to read every line —
 * but a silent cut would let it clear a file it never saw, so truncation is
 * always stated in the prompt.
 */
const MAX_GENERATED_BYTES = 24 * 1024;

export async function collectSpecArtifacts(
  featureName: string,
  specName: string,
  specYaml: string,
  cwd: string,
): Promise<SpecArtifacts> {
  const live = isLive(specYaml);
  if (live) return { specYaml, generated: [], live };
  return { specYaml, generated: await readGenerated(featureName, specName, cwd), live };
}

function isLive(specYaml: string): boolean {
  try {
    return parseTestSpec(specYaml).mode === "live";
  } catch {
    // An unparsable spec is audited as-is; assuming "not live" only means the
    // generated files are looked for, which is harmless when there are none.
    return false;
  }
}

/**
 * The generated files for one spec, newest contract first.
 *
 * An external target records what it wrote in `generated.json`, including
 * `support` files (page objects and the like) that the tests lean on — those
 * name selectors too, which is why the manifest keeps them. Without a manifest
 * the built-in target's `test.spec.ts` sits in the spec directory.
 */
async function readGenerated(
  featureName: string,
  specName: string,
  cwd: string,
): Promise<Array<{ path: string; content: string }>> {
  const specDir = getSpecDir(featureName, specName, cwd);
  const paths = (await manifestPaths(specDir, cwd)) ?? [join(specDir, "test.spec.ts")];

  const out: Array<{ path: string; content: string }> = [];
  let used = 0;
  for (const path of paths) {
    const content = await readFile(path, "utf8").catch(() => null);
    if (content === null) continue;
    if (used >= MAX_GENERATED_BYTES) break;
    const room = MAX_GENERATED_BYTES - used;
    out.push({
      path: relativeToCwd(path, cwd),
      content: content.length <= room ? content : `${content.slice(0, room)}\n… truncated`,
    });
    used += Math.min(content.length, room);
  }
  return out;
}

async function manifestPaths(specDir: string, cwd: string): Promise<string[] | null> {
  const raw = await readFile(join(specDir, GENERATED_MANIFEST_FILE), "utf8").catch(() => null);
  if (raw === null) return null;
  const parsed = GeneratedManifestSchema.safeParse(JSON.parse(raw));
  if (!parsed.success) return null;
  return parsed.data.files.map((f) => join(cwd, f.path));
}

function relativeToCwd(path: string, cwd: string): string {
  return path.startsWith(`${cwd}/`) ? path.slice(cwd.length + 1) : path;
}
