import { readFile } from "node:fs/promises";
import { relative, resolve } from "node:path";
import { loadProjectConfig, targetConfigFor, type ProjectConfig, type TargetConfig } from "../config/project-config.ts";
import type { TestCase } from "../cases/case.ts";
import { openCaseReader, type CaseReader } from "../cases/reader.ts";
import { registryFor, resolveTarget } from "../targets/registry.ts";
import { resolveCaseRecordingPath, resolveCaseTestPath } from "../targets/test-path.ts";
import {
  collectSupportFiles,
  loadTsconfigPaths,
  type TsconfigPaths,
} from "../targets/support-files.ts";
import type { TargetPlugin } from "../targets/types.ts";
import { caseIdOf, type SpecTarget } from "./types.ts";
import * as log from "../cli/logger.ts";

/**
 * The files that together make up one test case, as a drift audit sees them.
 *
 * A recorded case is two artifacts: the document its author wrote, and the
 * code `ccqa generate` compiled from a recording. The document describes
 * intent in prose; the generated code holds the literal selectors that
 * actually run. They drift independently, so auditing only the document
 * leaves the half that breaks a replay unexamined.
 *
 * A case run live has no second artifact — Claude drives it from the document
 * every time, so the document *is* the test.
 */
export interface SpecArtifacts {
  /**
   * What states the case. Both kinds say the same thing in different
   * vocabularies, and the audit reads the file verbatim either way — the
   * headings a project chose are part of what its author meant.
   */
  intent: { kind: CaseDocumentKind; path: string; body: string };
  /** Empty for a live case, and for a recorded case that has not been generated yet. */
  generated: Array<{ path: string; content: string }>;
  /**
   * The import each file was reached through — the entry's `from` is itself.
   * Provenance only: whether a file was read is `generated` versus
   * `unaudited`, and saying it a third time here is a third thing to keep
   * true. Kept so `--dump-inputs` can answer "why is this file here", which
   * is the question behind "did it even reach the audit".
   */
  reached: Array<{ path: string; from: string }>;
  /**
   * Files that belong to this test case but did not fit the byte budget. The
   * audit is told their names: a file it never saw must not read as one it
   * cleared.
   */
  unaudited: string[];
  live: boolean;
  /** Null when the document cannot be parsed. Carried into the report so a drift row
   * reads as the test case it audited, not as its directory path. */
  title: string | null;
}

/**
 * Which document states the case: ccqa's own `spec.yaml`, or one the project
 * writes itself in a format ccqa does not know. The audit reads both verbatim;
 * the difference is only in how the prompt introduces what it is looking at.
 */
export type CaseDocumentKind = "spec" | "project";

/**
 * Total generated bytes handed to the audit. Generated suites can run long, and
 * the audit's job is to check the strings they name, not to read every line —
 * but a silent cut would let it clear a file it never saw, so what is dropped
 * is always named in `unaudited`.
 */
const MAX_GENERATED_BYTES = 64 * 1024;

/**
 * What a whole sweep shares: the project's config, its import aliases, and the
 * reader every case is read through. None can change while specs are being
 * audited, and all three would otherwise be re-read per spec.
 */
export interface SpecArtifactsContext {
  config: ProjectConfig;
  tsconfig: TsconfigPaths | null;
  reader: CaseReader;
}

/**
 * Read the sweep-wide inputs once, before the first spec. A caller that
 * already holds a reader passes it, so its cases are read once for the whole
 * command rather than once per phase.
 */
export async function loadSpecArtifactsContext(
  cwd: string,
  reader?: CaseReader,
): Promise<SpecArtifactsContext> {
  const [config, tsconfig] = await Promise.all([loadProjectConfig(cwd), loadTsconfigPaths(cwd)]);
  return { config, tsconfig, reader: reader ?? openCaseReader(config, cwd) };
}

/**
 * Read one case's documents. Throws when the document itself cannot be read —
 * a case enumerated and then gone is an error to report, not an empty audit.
 *
 * A document that is there but will not parse is still audited: what its
 * author wrote is what the audit is for, and refusing to look at it would
 * clear a case nobody read.
 */
export async function collectCaseArtifacts(
  target: SpecTarget,
  cwd: string,
  ctx: SpecArtifactsContext,
): Promise<SpecArtifacts> {
  const read = await ctx.reader.read(caseIdOf(target));
  if (read.document === null) throw new Error(read.error ?? `${caseIdOf(target)}: no such test case`);
  const kind: CaseDocumentKind = ctx.reader.target ? "project" : "spec";
  const intent = { kind, path: relative(cwd, read.document.path), body: read.document.text };
  const testCase = read.case;
  const live = testCase?.mode === "live";
  const title = testCase?.title ?? null;
  if (live) return { intent, generated: [], unaudited: [], reached: [], live, title };
  return { intent, ...(await readGenerated(testFileOf(testCase, ctx, cwd), cwd, ctx)), live, title };
}

/**
 * The generated half alone, for a caller that brings its own account of what
 * happened — the failure classifier, which reads the same code the audit does.
 */
export async function collectGeneratedFor(
  caseId: string,
  cwd: string,
  ctx: SpecArtifactsContext,
): Promise<Pick<SpecArtifacts, "generated" | "unaudited" | "reached">> {
  const read = await ctx.reader.read(caseId);
  if (read.case === null && read.error !== null) log.warn(`${caseId}: ${read.error}`);
  return readGenerated(testFileOf(read.case, ctx, cwd), cwd, ctx);
}

/**
 * Where this case's files live, resolved through the target that owns them.
 *
 * All three together because one target resolution answers all three, and a
 * case that has one must not be reported as missing another. Every path is
 * null when nothing resolves — an unreadable case must cost its own paths,
 * not the sweep.
 */
async function caseFiles(
  target: SpecTarget,
  ctx: SpecArtifactsContext,
): Promise<{ testPath: string | null; recordingPath: string | null; writeRoots: readonly string[] }> {
  const none = { testPath: null, recordingPath: null, writeRoots: [] };
  const read = await ctx.reader.read(caseIdOf(target));
  // Said out loud: with no paths, a finding about this case is routed as if
  // there were no generated code to repair, which is a different verdict.
  if (read.case === null && read.error !== null) log.warn(`${caseIdOf(target)}: ${read.error}`);
  const testCase = read.case;
  const owner = testCase && targetOf(testCase, ctx);
  if (!testCase || !owner) return none;
  try {
    return {
      testPath: resolveCaseTestPath(owner.plugin, owner.targetConfig, testCase.ref.id),
      recordingPath: resolveCaseRecordingPath(owner.plugin, owner.targetConfig, testCase.ref.id),
      writeRoots: owner.targetConfig.writeRoots,
    };
  } catch {
    return none;
  }
}

/**
 * Where this case's generated test lives, project-relative — or null when it
 * has none (a live case, or a document whose target cannot be resolved).
 */
export async function caseTestPath(
  target: SpecTarget,
  ctx: SpecArtifactsContext,
): Promise<string | null> {
  return (await caseFiles(target, ctx)).testPath;
}

/**
 * Where this case's recording lives, project-relative, resolved through the
 * same target as its test — null on the same terms as {@link caseTestPath}.
 */
export async function caseRecordingPath(
  target: SpecTarget,
  ctx: SpecArtifactsContext,
): Promise<string | null> {
  return (await caseFiles(target, ctx)).recordingPath;
}

/**
 * Where this case's test lands, and where its target lets ccqa write: the two
 * halves of "which files a finding about this case could be repaired in".
 */
export async function caseWriteArea(
  target: SpecTarget,
  ctx: SpecArtifactsContext,
): Promise<{ testPath: string | null; writeRoots: readonly string[] }> {
  const { testPath, writeRoots } = await caseFiles(target, ctx);
  return { testPath, writeRoots };
}

/**
 * The target that owns this case's generated files.
 *
 * A case the project states itself belongs to the target that declared the
 * source; a `spec.yaml` case names its own. Null when nothing resolves — an
 * unreadable target must cost this one case's paths, not the sweep.
 */
function targetOf(
  testCase: TestCase,
  ctx: SpecArtifactsContext,
): { plugin: TargetPlugin; targetConfig: TargetConfig } | null {
  if (ctx.reader.target) {
    const plugin = registryFor(ctx.config).get(ctx.reader.target.id);
    return plugin ? { plugin, targetConfig: ctx.reader.target.targetConfig } : null;
  }
  if (testCase.spec === null) return null;
  try {
    const plugin = resolveTarget(testCase.spec, ctx.config);
    return { plugin, targetConfig: targetConfigFor(ctx.config, plugin.id) };
  } catch {
    return null;
  }
}

/** The generated test's absolute path, or null when this case compiles into none. */
function testFileOf(
  testCase: TestCase | null,
  ctx: SpecArtifactsContext,
  cwd: string,
): string | null {
  if (testCase === null) return null;
  const owner = targetOf(testCase, ctx);
  if (owner === null) return null;
  try {
    return resolve(cwd, resolveCaseTestPath(owner.plugin, owner.targetConfig, testCase.ref.id));
  } catch {
    return null;
  }
}

/**
 * The code this case runs: the test at the target's `testPath`, then whatever
 * it imports from inside the project. A page object names selectors too, and an
 * audit that stopped at the test file would clear strings it never read.
 */
async function readGenerated(
  testAbs: string | null,
  cwd: string,
  ctx: SpecArtifactsContext,
): Promise<Pick<SpecArtifacts, "generated" | "unaudited" | "reached">> {
  if (testAbs === null) return { generated: [], unaudited: [], reached: [] };
  const files = [
    { abs: testAbs, from: testAbs },
    ...(await collectSupportFiles(testAbs, cwd, { tsconfig: ctx.tsconfig })),
  ];
  // Read together, spend the budget in order: the reads are independent, but
  // which file falls outside the budget must not depend on who finished first.
  const contents = await Promise.all(
    files.map((f) => readFile(f.abs, "utf8").catch(() => null)),
  );

  const generated: Array<{ path: string; content: string }> = [];
  const unaudited: string[] = [];
  const reached: SpecArtifacts["reached"] = [];
  let used = 0;
  for (const [i, content] of contents.entries()) {
    // A path that cannot be read is not part of the case: the walker resolves
    // an import before listing it, so in practice this is the entry of a spec
    // that was never generated — which `unaudited` must not claim exists.
    if (content === null) continue;
    const file = files[i]!;
    const display = relative(cwd, file.abs);
    const from = file.abs === file.from ? "(entry)" : relative(cwd, file.from);
    reached.push({ path: display, from });
    if (used + content.length > MAX_GENERATED_BYTES) {
      unaudited.push(display);
      continue;
    }
    generated.push({ path: display, content });
    used += content.length;
  }
  return { generated, unaudited, reached };
}

